export const locators = {
  loginBtn: '#nav-buttons > li.nav__item.login-button',
  emailInput: '#login-email',
  passwordInput: '#login-password',
  submitBtn: '//button[text()="Log in"]',
  appCatalog: "//div[@class='appCatalog']",
  createCollectionBtn: 'collectionCreate',
  collectionMenu: 'menuOpener',
  collectionDeleteItem: "collectionDelete",
  collectionNameInput: 'input[name="collectionName"]',
  saveCollectionBtn: '//div[@class="PicsioTreeItem__edit"]/div[@class="PicsioTreeItem__actions"]/div[2]/button',
  collectionName: '//p[text()="{collectionName}"]',
  collectionDirIcon: '//p[text()="{collectionName}"]/preceding-sibling::i[1]',
  collectionNameItem: '//p[text()="{collectionName}"]/parent::div/parent::div/parent::div[@class="PicsioTreeItem__content"]',
  toolbarActionUpload: '//div[@class="toolbarActions"]//button[@data-testid="collectionUpload"]',
  uploadFilesMenuItem: '//input[@type="file" and @multiple]',
  totalAssetsCountText: '//div[@class="importNumberFiles"]',
  importSubmitBtn: '//button[@data-testid="importSubmit"]',
  tiles: '#tiles',
  catalogItem: "//div[@id='tiles']/div[contains(@class, 'catalogItem')][{index}]",
  dialogConfirmBtn: '//span[text()="Confirm"]/parent::button',
  dialogDeleteBtn: '//span[text()="Delete"]/parent::button',
  spinner: '//div[@class="innerPicsioSpinner"]',
} as const;
